name: 'Deploy flows'
branding:
  icon: cloud
  color: blue
description: 'Deploy flows to Prefect Cloud and Google Cloud Run'
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  flow_entrypoint:
    description: 'Prefect flow entrypoint e.g. myflow.py:flow_function'
    required: true
  deployment:
    description: 'Prefect deployment name - could reference environment or branch name e.g. dev or prod'
    required: false
    default: default
  queue:
    description: 'Prefect queue name'
    required: false
    default: default
  storage_block:
    description: 'Name of the storage block'
    required: false
    default: "github/default"
  infrastructure_block:
    description: 'Name of the infrastructure block'
    required: false
    default: "cloud-run-job/default"
  python_version:
    description: 'Python version'
    required: false
    default: "3.10"  # the latest Prefect 2 version is used by default
  install_command:
    description: 'Can be set to e.g. pip install -r requirements.txt'
    required: false
    default: "pip install ."  # install via setup.py by default
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    # Setup miniconda build env
    - uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        miniconda-version: py310_23.3.1-0
        mamba-version: "*"
        channels: conda-forge
        activate-environment: xmatics
        environment-file: environment.yml

    - id: activate-xmatics
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate xmatics
        poetry install


    - id: login-prefect
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate xmatics
        prefect config set PREFECT_API_KEY=${{ inputs.prefect_api_key }}
        prefect config set PREFECT_API_URL=${{ inputs.prefect_api_url }}
      shell: bash

    - run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate xmatics
        prefect deployment build ${{ inputs.flow_entrypoint }} -n ${{ inputs.deployment }} -q ${{ inputs.queue }} \
        -sb "${{ inputs.storage_block }}" -ib "${{ inputs.infrastructure_block }}" --skip-upload -a -v $GITHUB_SHA
      shell: bash
